# we use the basic isaaclab image as the base
FROM isaac-lab-base AS base

# Install whatever you need as additional dependencies.

# make working directory as the Isaac Lab directory
# this is the default directory when the container is run
WORKDIR /workspace
